### ISSUE TITLE
change Futura font to Didact Gothic

### ISSUE THREAD

**Issue by katherineobermeyer** [ferni/makerdai.org#41]
Futura is $$$, Didact Gothic is open source and visually similar https://fonts.google.com/specimen/Didact+Gothic

**Comment by go0t** [comment]
Here is a mockup using Didact Gothic:
https://invis.io/8CC3VCY5X#/239400231_04_Didactic

Since it only has a "Regular" Font-weight, it lacks the strength and boldness that Futura has.

Here are some other open source alternatives.
Muli: https://invis.io/8CC3VCY5X#/239400229_02_Muli
Nunito: https://invis.io/8CC3VCY5X#/239400230_03_Nunito
Open Sans: https://invis.io/8CC3VCY5X#/239400232_Open_Sans

I highly recommend getting a license for Futura.

**Comment by matttrichards** [comment]
we purchased futura - please close this
